services:
  app:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/eastzoo/files/${PROJECT_NAME}/uploads:/usr/src/app/uploads
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
