service: haedal-api
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-warmup
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs18.x
  environment:
    NODE_ENV: ${env:NODE_ENV}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_DATABASE}

    JWT_SECRET: ${env:JWT_SECRET}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
    SECRET_KEY: ${env:SECRET_KEY}

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /
